server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/AngelVilchesU/TINGESO_EVAL2_CONFIG-SERVER
          search-paths: config-data
  application:
    name: config-service